language: ruby
rvm:
  - "2.0.0"
env:
  - WOODSMAN_USER=foo WOODSMAN_PASSWORD=bar WOODSMAN_TUMBLR_HOST=http://example.tumblr.com
before_script:
  - cp config/database.yml.example config/database.yml
  - psql -c 'create database woodsman_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate